### ISSUE TITLE
_onTap & _ondoubleTap

### ISSUE THREAD

**Issue by Gregor4711** [aleksanderwozniak/simple_gesture_detector#3]
great widged. Easy to adapt / use , Thank you.
I can't use _onTap and _ondoubleTap event. Is already implemented?

BR JB

**Comment by aleksanderwozniak** [comment]
Hi,

Yes, both of those are implemented and should be working.
Check out [example project](https://github.com/aleksanderwozniak/simple_gesture_detector/blob/9e4596cdbca4056530b5c1960b5bf8a73bc32e22/example/lib/main.dart#L79). It doesn't actually use neither of those, but it should show you how to add a callback.
