### ISSUE TITLE
PageView is not working.

### ISSUE THREAD

**Issue by iamafzalhassan** [aleksanderwozniak/simple_gesture_detector#5]
**PageView** is not working after implementing **simple_gesture_detector** I used below implementation for **PageView**.

https://medium.com/flutter-community/flutter-pageview-widget-e0f6c8092636

Please let me know how to resolve this issue.

**Comment by aleksanderwozniak** [comment]
How exactly is it not working? Are you capturing the same gesture twice? 

Please provide a self-contained code snippet that will allow to reproduce this problem.

**Comment by imakevirtual** [comment]
> How exactly is it not working? Are you capturing the same gesture twice?
> 
> Please provide a self-contained code snippet that will allow to reproduce this problem.

**Comment by iamafzalhassan** [comment]
[pagehome.txt](https://github.com/aleksanderwozniak/simple_gesture_detector/files/6392347/pagehome.txt)
[pageroute.txt](https://github.com/aleksanderwozniak/simple_gesture_detector/files/6392352/pageroute.txt)



I just want to close an **AlertDialog** when user swipe the page. If I remove **onHorizontalSwipe** option, I can swipe the page otherwise I can't. The **PageHome** inside in PageView array.

**Comment by aleksanderwozniak** [comment]
Try setting the [hit test behavior](https://pub.dev/documentation/simple_gesture_detector/0.2.0/simple_gesture_detector/SimpleGestureDetector/behavior.html) to `HitTestBehavior.translucent`.

**Comment by iamafzalhassan** [comment]
Not working bro.

**Comment by aleksanderwozniak** [comment]
In that case you might need to use PageView's `onPageChanged`.
